DELETE {
	?s1 nmo:sender ?email .
}
INSERT {
	?s1 nmo:sender ?node .
	?node rdfs:label ?email .
}
WHERE {
	
	{
		SELECT ?email (uuid() as ?node)
		{
			?s nmo:sender ?email .
			?s a nmo:Email .
		}
		GROUP BY ?email
	}

	?s1 nmo:sender ?email .
	?s1 a nmo:Email .
}
