CONSTRUCT {
	?node :p-count ?count .
	?node rdfs:label ?value .
	?node rdfs:member ?s1
}
FROM notepad:sameas-starting-point
WHERE {
	
	{
		SELECT (count(?s) as ?count) ?value (uuid() as ?node)
		# Note sure whether bnode() is better than uuid().  It doesn't display correctly in notepad.
		{
			?s :p ?value .
			?s a :to-consider-identical .
		}
		GROUP BY ?value
	}

	?s1 a :to-consider-identical .

	?s1 :p ?value .

}
