WITH notepad:sameas-starting-point

DELETE 
	{ ?s ?p ?o }
INSERT {
	:u1 :p "value1" ; a :to-consider-identical .
	:u2 :p "value1" ; a :to-consider-identical .

	:u3 :p "value2" ; a :to-consider-identical .
	:u4 :p "value2" ; a :to-consider-identical .

	:n5 :p "value1" ; a :to-keep-distinct .

	:n6 :p "value2" ; a :to-keep-distinct .
	:n7 :p "value2" ; a :to-keep-distinct .
}
WHERE
	{ ?s ?p ?o }
