PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 

SELECT DISTINCT ?predicate ?label
WHERE {
  bind ( 'rdfs:member' as ?predicate ).

  ?predicate rdfs:label ?label .
  { ?s ?predicate ?o } UNION { ?predicate a rdf:Property } .
  # optional { ?predicate owl:inverseOf [ rdfs:label ?inverseLabel ] } .
}