PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ex: <http://example.com/#>
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/nmo/#>
PREFIX notepad: <http://www.vonholzen.org/instruct/notepad/#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX : <file://localhost/Users/holzen/git/notepad/notepad/tests/notepad.html#>
PREFIX : <file://localhost/Users/holzen/git/notepad/notepad/tests/notepad.html#> 
CONSTRUCT { 
	?about ?predicateForward ?neighbourForward . 
	?neighbourBackward ?predicateBackward ?about . 
	?neighbour nmo:sender ?sender .
} 
WHERE { 
 
	LET ( ?about := <http://localhost:3030/dev/699676b0-13f0-11e2-9b2e-c82a1402d8a8> ) 
 
	{ ?about ?predicateForward ?neighbourForward 
		BIND (?neighbourForward as ?neighbour) 
	} 
	UNION 
	{ ?neighbourBackward ?predicateBackward ?about 
		BIND (?neighbourBackward as ?neighbour) 
#		FILTER NOT EXISTS { ?neighbourBackward a notepad:Session } 
	} 
 
	# Ignore  
 
 
  { ?neighbour <http://www.semanticdesktop.org/ontologies/nmo/#sender> ?sender }
  	# ?sender FILTER regex(?sender, "\"William Gregory\" ") } 
  	# "\"William Gregory\" "}
}