# test sameAs

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX ex:	 <http://example.com/#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

INSERT DATA {
	ex:a1 ex:predicate "123" .
	ex:a2 owl:sameAs ex:a1 .
}


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX ex:	 <http://example.com/#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

CONSTRUCT { ex:a1 ?p ?o
}
WHERE {
	ex:a1 ?p ?o
}
