INSERT DATA { GRAPH <ex:12ce5201-d741-175d-1cf6-39ba362ecac4>
	{_:_569e91a0-13ae658cb65__6245 <http://www.vonholzen.org/instruct/notepad/#filterByPredicate1> <http://www.vonholzen.org/instruct/notepad/#filterByPredicate1> .}
}
