CONSTRUCT {
	?subject ?labelPredicate ?label ;
			 notepad:reason ?reason .
}
WHERE {
    ?subject ?labelPredicate ?label
    FILTER (
    	isLiteral(?label) &&
    	?labelPredicate NOT IN (nmo:htmlMessageContent, nmo:plainTextMessageContent) &&
    	regex(?label, "{{{term}}}", "i")
    )
    BIND (substr(?label, 0, 100) as ?reason)
}
LIMIT 30