CONSTRUCT {
	?subject a rdf:subject .
	?subject rdfs:label str(?subject) .

	?predicate a rdf:predicate .
	?predicate rdfs:label str(?predicate) .

	?object a rdf:object .
	?object rdfs:label str(?object) .
}
WHERE {
	{	 
		?subject ?anyPredicate ?anyObject 
		FILTER regex(str(?subject), "{{{rdfs:label}}}", "i")
	} 
	UNION
	{	
		?anySubject ?predicate ?anyObject
		FILTER regex(str(?predicate), "{{{rdfs:label}}}", "i")
	}
	UNION
	{
	    ?anySubject ?anyPredicate ?object
	    FILTER regex(?label, "{{{rdfs:label}}}", "i")

	    # We could add that ?anyPredicate subPropertyOf rdfs:label
	}
}
LIMIT 30